@startuml
skinparam classAttributeIconSize 0

class SP
class QPS
class PKB

abstract class IPKBPopulator {
	+void populate(Abstraction)
}

abstract class IPKBQuerier {
	+Results query(Query)
}

class PKB {
    -EntityManager entity_manager_
    -PatternManager pattern_manager_
    -RelationshipManager relationship_manager_
    +void populate(Abstraction)
    +Results query(Query)
}

class EntityManager {
    -unordered_map entity_map_ 
    -void CreateTable(EntityType)
    +EntityTable* GetTable(EntityType) 
    +void populate(Entity)
    +Results query(Query)
}

class RelationshipManager {
    -unordered_map relationship_map_
    -void CreateTable(RsType)
    +RelationshipTable* GetTable(RsType) 
    +void populate(Relationship)
    +Results query(Query)
}

class PatternManager {
    +PatternTable* GetTable()
    +void populate(Pattern)
    +Results query(Query)
}

class RelationshipTable {
    #EntityPointerUnorderedMap table_
    #EntityPointerUnorderedMap inverse_table_
    +void Populate(Relationship)
    +EntityPointerUnorderedMap GetTable(bool)
}

class EntityTable {
    #EntityPointerUnorderedSet table_
    +void Populate(Entity)
    +EntityPointerUnorderedSet get()
}

class PatternTable {
    #PatternEntityUnorderedMap pattern_table_
    +void Populate(Pattern)
    +PatternEntityUnorderedMap GetTable()
}

abstract class "QueryPattern"

class VariableTable {
}

class ReadTable {
}

class PrintTable {
}

class CallTable {
}

class IfTable {
}

class WhileTable {
}

class ConstantTable {
}

class ProcedureTable {
}

class AssignTable {
}

class ModifiesTable {
}

class FollowsTable {
}  

class UsesTable {
}

class ParentTable {
} 

IPKBPopulator *-down- PKB
IPKBQuerier *-down- PKB
SP -down- IPKBPopulator
QPS -down- IPKBQuerier

PKB <|.down EntityManager
PKB <|.down.  PatternManager
PKB <|.down.. RelationshipManager

EntityTable -up-* EntityManager

VariableTable -up-|> EntityTable
ReadTable -up-|> EntityTable
PrintTable -up-|> EntityTable
CallTable -up-|> EntityTable
IfTable -up-|> EntityTable
WhileTable -up-|> EntityTable
ConstantTable -up-|> EntityTable
ProcedureTable -up-|> EntityTable
AssignTable -up-|> EntityTable

RelationshipTable -up-* RelationshipManager 

ModifiesTable -up-|> RelationshipTable
FollowsTable -up-|> RelationshipTable 
UsesTable -up-|> RelationshipTable
ParentTable -up-|> RelationshipTable 

PatternTable -up-* PatternManager
PatternTable -down-|> QueryPattern

@enduml