@startuml
!include Style.puml
!include SequenceStyle.puml

box QPS QPS_COLOR_LIGHT
participant ":QPS" as QPS<<QPS>>
participant ":QueryLexer" as QueryLexer<<QPS>>
participant ":QueryParser" as QueryParser<<QPS>>
participant ":QueryBuilder" as QueryBuilder<<QPS>>
participant ":QueryEvaluator" as QueryEvaluator<<QPS>>
end box

box PKB PKB_COLOR_LIGHT
participant ":PKB" as PKB<<PKB>>
end box

[-> QPS : ExecuteQuery()
activate QPS

QPS -> QueryLexer : Lex()
activate QueryLexer
QueryLexer -> QueryLexer : NextToken()
QueryLexer --> QPS : tokens
deactivate QueryLexer

QPS -> QueryParser : Parse(Token[])
activate QueryParser
QueryParser -> QueryBuilder : Build()
activate QueryBuilder
QueryBuilder --> QueryParser : Query
deactivate QueryBuilder
QueryParser --> QPS : Query
deactivate QueryParser

QPS -> QueryEvaluator : Evaluate(Query)
activate QueryEvaluator
QueryEvaluator --> QPS : Result
deactivate QueryEvaluator


[<-- QPS : Result
deactivate QPS

@enduml