@startuml

abstract class Node {
    NodeType node_type_
    NodeType GetNodeType()
    Node[] GetChildren()
    void VisitAll(Function<Node, void>)
    void VisitChildren(Function<Node, void>)
    String ToString()
}

class ProgramNode
class ProcedureNode
class StmtListNode
class StatementNode
class CondExprNode
class RelFactorNode

'base nodes
ProgramNode -up-|> Node
ProcedureNode -up-|> Node
StmtListNode -up-|> Node
StatementNode -up-|> Node
CondExprNode -up-|> Node
RelFactorNode -up-|> Node

@enduml