@startuml

abstract class Node {
    -NodeType node_type_
    +NodeType GetNodeType()
    +std::vector<Node*> GetChildren()
    +std::string ToString()
    +void VisitAll(std::function<void(Node *)>)
    +void VisitChildren(std::function<void(Node *)>)
}

class ProgramNode
class ProcedureNode
class StmtListNode
class StatementNode
class CondExprNode
class RelFactorNode

'base nodes
ProgramNode .up.|> Node
ProcedureNode .up.|> Node
StmtListNode .up.|> Node
StatementNode .up.|> Node
CondExprNode .up.|> Node
RelFactorNode .up.|> Node

@enduml