@startuml

abstract class Node
class SymbolNode
class LiteralNode
class CallNode
class AssignNode
class ReadNode
class PrintNode
class IfNode
class WhileNode
class ProcedureNode
class StmtListNode

'base nodes
ProgramNode .up.|> Node
ProcedureNode .up.|> Node
StmtListNode .up.|> Node
StatementNode .up.|> Node
CondExprNode .up.|> Node
RelFactorNode .up.|> Node

'atomic nodes
ReferenceNode ..up.|> RelFactorNode
SymbolNode .up.|> ReferenceNode
LiteralNode .up.|> ReferenceNode

'expression nodes
ExprNode ..up.|> RelFactorNode
PlusNode .up.|> ExprNode
MinusNode .up.|> ExprNode
TimesNode .up.|> ExprNode
DivNode .up.|> ExprNode
ModNode .up.|> ExprNode

'cond expr nodes
NotExprNode .up.|> CondExprNode
BinaryCondExprNode .up.|> CondExprNode
RelExprNode .up.|> CondExprNode

'statements
CallNode ..up..|> StatementNode
AssignNode ..up..|> StatementNode
ReadNode ..up..|> StatementNode
PrintNode ..up..|> StatementNode
IfNode ..up..|> StatementNode
WhileNode ..up..|> StatementNode

@enduml