@startuml

abstract class Node {
    NodeType node_type_
    NodeType GetNodeType()
    Node[] GetChildren()
    void VisitAll(Function<Node, void>)
    void VisitChildren(Function<Node, void>)
    String ToString()
}

class CFGNode {
    Entity stmt_
    Entity GetStmt()
    void AddChild(Node)
    void SetChild(Node *, int)
    bool IsTerminal()
}

Node <|-down- CFGNode

@enduml