@startuml

interface UI
interface IPKBPopulator

class SP
class Lexer
abstract class Token
Token <|.. Symbol
Token <|.. Literal
Token <|.. Keyword
Token <|.. Operator
Token <|.. Separator

class Parser
class EntityExtractor
class PatternExtractor
class RelationshipExtractor

SP -up-> IPKBPopulator
SP <-up- UI: LoadSource

SP -down-> Lexer: lex()
SP -down-> Parser: ParseProgram()
SP -down-> Extractor: ExtractAll()

Lexer o-- Token
Parser -down-> ProgramGrammarRule: parseNode()

Extractor <|.. EntityExtractor
Extractor <|.. PatternExtractor
Extractor <|.. RelationshipExtractor

@enduml

