@startuml

class SP
class UI
class PKB

class UIInterface {
    string readSourceFile()
}

class Lexer {
    Token getNext()
    Token[] lex()
}

abstract class Token {
}
class Symbol
class Literal
class Keyword
class Operator
class Separator

class Parser
class GrammarRule

class SimpleAST

class DesignExtractor {
    DesignAbstraction[] extractDesign(SimpleAST)
}
abstract class AbstractExtractor {
    DesignAbstraction extract(SimpleAST)
}
class EntityExtractor {
}
class PatternExtractor {
}
class RelationshipExtractor {
}

class PKBInterface

SP *-left- UIInterface
SP *-left- PKBInterface
SP *-down- Lexer
SP *-down- Parser
SP *-right- DesignExtractor
PKBInterface -up- PKB
UIInterface -up- UI

Token <|.. Symbol
Token <|.. Literal
Token <|.. Keyword
Token <|.. Operator
Token <|.. Separator

Lexer o-- Token
Parser .left.> Lexer: getNext()
Parser -down-> GrammarRule : check()
Parser *-down-> SimpleAST

AbstractExtractor <|.. EntityExtractor
AbstractExtractor <|.. PatternExtractor
AbstractExtractor <|.. RelationshipExtractor

DesignExtractor --> AbstractExtractor : extract()

@enduml

