@startuml

[User Interface] as UI

package "Query Processing System" {
    port IQps
    [Query Processing System] as QPS
    [QueryLexer]
    [QueryParser]
    [QueryBuilder]
    [QueryEvaluator]
}

package "Source Processor" {
    port ISp
    [Source Processor] as SP
    [SimpleLexer]
    [SimpleParser]
    [Extractor]
}

database "Program Knowledge Base" {
  [Program Knowledge Base] as PKB
  port IPkbPopulator
  port IPkbQuerier
  [Entity Manager] --> [Entity Stores]
  folder "Entity Stores" {
    [VariableStore]
    [ConstantStore]
    [ProcedureStore]
    [StatementStore]
  }
  [Relationship Manager] --> [Relationship Tables]
  folder "Relationship Tables" {
    [UsesTable]
    [ModifiesTable]
    [CallsTable]
    [ParentTable]
    [FollowsTable]
  }
  [Pattern Manager] --> [Pattern Store]
  folder "Pattern Store" {
  }
}

[UI] --down--> [ISp] : LoadSource
[UI] --down--> [IQps] : EvaluateQuery

[IPkbPopulator] -down-> [PKB]
[IPkbQuerier] -down-> [PKB]
[PKB] -down-> [Entity Manager]
[PKB] -down-> [Relationship Manager]
[PKB] -down-> [Pattern Manager]

[ISp] -down-> [SP]
[SP] -down-> [SimpleLexer]
[SP] -down-> [SimpleParser]
[SP] -down-> [Extractor]
[SP] -down--> IPkbPopulator

[IQps] -down-> [QPS]
[QPS] -down-> [QueryLexer]
[QPS] -down-> [QueryParser]
[QPS] -down-> [QueryBuilder]
[QPS] -down-> [QueryEvaluator]
[QueryEvaluator] -down-> IPkbQuerier

@enduml