name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on:
  pull_request:
    branches:
      - master
    paths:
      - 'Team14/**'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Build Project
        shell: bash
        run: |
          chmod +x scripts/build.sh
          scripts/build.sh

      - uses: ZedThree/clang-tidy-review@v0.9.0
        id: review
        with:
          build_dir: build
          exclude: "catch.hpp"
          clang_tidy_version: 12
          config_file: ".clang-tidy"
          max_comments: 5
      
      # If there are any comments, fail the check
      - if: steps.review.outputs.total_comments > 0
        run: exit 1