name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on:
  pull_request:
    branches:
      - master
  workflow_run:
    workflows: [ "Linux Build" ]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: ZedThree/clang-tidy-review@v0.9.0
        id: review
        with:
          build_dir: build
          exclude: "catch.hpp"
          clang_tidy_version: 11
      
      # If there are any comments, fail the check
      - if: steps.review.outputs.total_comments > 0
        run: exit 1