name: telegram alert

on:
  pull_request:
    branches:
      - master
    types: [ opened ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on pull_request
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created a new commit.
            Commit message: ${{ github.event.pull_request.title }}
            
            Review now -> https://github.com/nus-cs3203/22s1-cp-spa-team-14/pulls